work_dir: ./work_dir/recognition/custom_skeleten/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150 
  # data_path: ./dataset/custom_skeleten_data/noSplitPerson_train_val/train_data.npy
  # label_path: ./dataset/custom_skeleten_data/noSplitPerson_train_val/train_label.pkl
  data_path: ./dataset/custom_skeleten_data/splitPerson_train_val/train_data.npy
  label_path: ./dataset/custom_skeleten_data/splitPerson_train_val/train_label.pkl
test_feeder_args:
  # data_path: ./dataset/custom_skeleten_data/noSplitPerson_train_val/val_data.npy
  # label_path: ./dataset/custom_skeleten_data/noSplitPerson_train_val/val_label.pkl
  data_path: ./dataset/custom_skeleten_data/splitPerson_train_val/val_data.npy
  label_path: ./dataset/custom_skeleten_data/splitPerson_train_val/val_label.pkl


# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 4
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

ori_model_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [0]
batch_size: 32 
test_batch_size: 32

#optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 50



